simple_block.settings:
  type: config_object
  label: 'Simple block Page Settings'
  mapping:
    email:
      type: text
      label: 'Email'
    message:
      type: text
      label: 'Message'
    langcode:
      type: string
      label: 'Language code'
